# Generated by Django 3.2.14 on 2022-07-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban_dashboard', '0002_user_table_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='task_id',
        ),
        migrations.CreateModel(
            name='UserTaskMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kanban_dashboard.task_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kanban_dashboard.user_table')),
            ],
        ),
    ]
