# Generated by Django 3.2.14 on 2022-07-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban_dashboard', '0003_auto_20220723_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_table',
            name='task_assignee',
        ),
        migrations.AddField(
            model_name='task_table',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Kanban_dashboard.user_table'),
        ),
        migrations.DeleteModel(
            name='UserTaskMap',
        ),
    ]
